FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY generador.py .

# -u fuerza a Python a imprimir los logs en tiempo real
CMD ["python", "-u", "generador.py"]